#!/bin/bash
#
#	Run the mbc Docker container, using the home volume found in this directory.
#
dir=$(cd `dirname $0`; pwd)
echo dir=${dir}
IMAGE_TAG=tooltwist/aws-explorer

# Leave command blank, to perform default startup
CMD=/bin/bash
CMD=

secretName=j-test-awsexplorer

#docker run -ti -p :4000 --rm -e SERVER_HOME=/Config/home juice-local-test /bin/sh
docker run -ti \
	-p 3000:3000 \
	--rm \
	-e GENERATE_AWS_CREDENTIALS=Y \
	-e AWS_PROFILE=personal \
	-e JUICE_CONFIG=secrets_manager:::ap-southeast-1:::${secretName} \
	${IMAGE_TAG} \
	${CMD}
